# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-16 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Entry',
        ),
    ]
